#!/usr/bin/env node
//  SuperTux
//  Copyright (C) 2026 ponyo877
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Asks Laya for its answer to every situation the game can describe and
// writes them to mk/emscripten/laya-table.js. The badguys' prompt only has a
// handful of possible inputs (see mk/emscripten/laya-prompt.js), so ?ai=laya
// can look the answers up in any browser instead of running the model.
//
//   cd tools/laya-server && uv run server.py        # in another terminal
//   node tools/laya-server/export-table.mjs
//
// Run it again whenever laya-prompt.js changes; the page refuses a table made
// for a different prompt.

import { writeFile } from "node:fs/promises";
import { createRequire } from "node:module";
import { fileURLToPath } from "node:url";

const require = createRequire(import.meta.url);
const prompt = require("../../mk/emscripten/laya-prompt.js");
const LAYA_URL = process.env.LAYA_URL || "http://127.0.0.1:8766/v1/systemone";
const output = fileURLToPath(new URL("../../mk/emscripten/laya-table.js", import.meta.url));

const situations = prompt.situations();
const questions = Object.fromEntries(situations.map((situation, i) => ["s" + i, prompt.question(situation)]));

let result;
try {
  const response = await fetch(LAYA_URL, {
    method: "POST",
    headers: { "Content-Type": "application/json" },
    body: JSON.stringify({ state: "", questions }),
  });
  if (!response.ok)
    throw new Error("HTTP " + response.status + " " + await response.text());
  result = await response.json();
} catch (error) {
  console.error(`Laya server at ${LAYA_URL} failed: ${error.message}`);
  console.error("Start it with: cd tools/laya-server && uv run server.py");
  process.exit(1);
}

const answers = {};
situations.forEach((situation, i) => {
  const { choice, confidence, probabilities } = result.answers["s" + i];
  answers[situation] = { type: "choice", choice, confidence, probabilities };
  console.log(`${choice.padEnd(8)} ${Math.max(...Object.values(probabilities)).toFixed(2)}  ${situation}`);
});

const table = {
  model: result.model,
  instructions: prompt.INSTRUCTIONS,
  criteria: prompt.CRITERIA,
  answers,
};
await writeFile(output,
  "// Generated by tools/laya-server/export-table.mjs from mk/emscripten/laya-prompt.js; do not edit.\n" +
  "window.LAYA_TABLE = " + JSON.stringify(table, null, 2) + ";\n");
console.log(`Wrote ${situations.length} answers from ${result.model} to ${output}`);
