//  SuperTux
//  Copyright (C) 2026 ponyo877
//
//  This program is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  This program is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//  GNU General Public License for more details.
//
//  You should have received a copy of the GNU General Public License
//  along with this program.  If not, see <http://www.gnu.org/licenses/>.

// Teaches one of Tux's tables to get through the whole level against
// several kinds of badguys, by the table's own mistakes (as DAgger does,
// with search.js's search as the teacher).
//
//   node tools/coevo/dagger.mjs --from <table> --name <new table> [--ai off,coevo4,table:<badguy table>] [--seeds 1]
//        [--rounds 60] [--tabs 6] [--beam 24] [--depth 10] [--turbo 20] [--delays 0,2]
//        [--noisy coevo4,table:<badguy table>] [--noise 0.03] [--noise-seeds 1,2,3]
//
// Every round, the table plays the level from the start against every kind
// of badguys (search.html?ai=...), in the very way search.mjs finds its
// sequences. Where it fails, the moves it made up to a little before are
// kept and a beam search looks for a way on from there, a few hundred
// pixels past where it failed; what Tux saw before each of those moves, and
// the move, go into the table. The search keeps the move of every
// situation the other runs (and this one, up to there) met, so it cannot
// break them; the change stays if the table then does better overall. It backs off further when nothing is found. The table is written
// after every change, with its finer facts (--from's, or 76 zones of 200 px).
//
// Needs the web build and tools/jev-proxy/server.mjs serving it on 8765.

import { chromium } from "playwright";
import { copyFile, readFile, writeFile } from "node:fs/promises";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const repo = resolve(here, "../..");
const build = join(repo, "build.wasm");
const tablesDir = join(here, "tables");
const args = Object.fromEntries(process.argv.slice(2).reduce((pairs, arg, i, all) =>
  arg.startsWith("--") ? [...pairs, [arg.slice(2), all[i + 1]]] : pairs, []));
const ais = (args.ai || "off,coevo4").split(",");
const seeds = (args.seeds || "1").split(",").map(Number);
// Waits (0.2 s each) before Tux starts, so the badguys are elsewhere when
// he gets to them: a table has to handle more than one timing.
const delays = (args.delays || "0").split(",").map(Number);
// Badguys that now and then do something else (jev-controller.js's ?noise=),
// played with each of the noise seeds: a table that gets through those too
// reacts to what the badguys do rather than counting on it.
const noisyAis = (args.noisy || "").split(",").filter(Boolean);
const noise = Number(args.noise || 0.03);
const noiseSeeds = (args["noise-seeds"] || "1,2,3").split(",").map(Number);
// Every page: a kind of badguys, or "<kind>~" for its noisy version.
const pageKinds = [...ais, ...noisyAis.map((ai) => ai + "~")];
const ROUNDS = Number(args.rounds || 60);
const tabs = Number(args.tabs || 6);
const BEAM = Number(args.beam || 24);
const DEPTH = Number(args.depth || 10);
// Steps between frames: with the Trained AI badguys, runs of 40 steps and
// more at once play out unlike real time; 20 and fewer play out as it does.
const TURBO = Number(args.turbo || 20);
const START = { x: 112, bottom: 576 };
const GOAL = 13380;      // the goal poles
const AHEAD = 500;       // px past a failure a way on has to get
const BACK_OFF = [2, 4, 7, 11, 16];  // moves given back before a failure
const MOVES = 9;
const CELL = 24;

const parse = (text) => JSON.parse(text.slice(text.indexOf("] = ") + 4, text.lastIndexOf(";")));
const teacher = parse(await readFile(join(tablesDir, `${args.from}.js`), "utf8"));
// The teacher's finer facts, or 76 zones of 200 px for a table without.
const table = { packed: teacher.packed, extra: teacher.extra || [["zone", Array.from({ length: 76 }, (_, i) => i)]],
                delta: { ...(teacher.extra ? teacher.delta : {}) } };
const zones = table.extra;

async function save() {
  const t = { ...teacher, ...table, model: `${args.from}, taught by its mistakes against ${ais.join(", ")} (dagger.mjs)` };
  await writeFile(join(tablesDir, `${args.name}.js`),
    "// Generated by tools/coevo/dagger.mjs; do not edit.\n" +
    "window.POLICY_TABLES = window.POLICY_TABLES || {};\n" +
    `window.POLICY_TABLES[${JSON.stringify(args.name)}] = ${JSON.stringify(t)};\n`);
}

// --- pages ------------------------------------------------------------------

const play = await readFile(join(build, "play.html"), "utf8");
const marker = /<script src="laya-prompt\.js[^"]*"><\/script>/;
// Everyone's counts and headstones stay out of automated play: headstones
// are objects in the level, and would change it.
const STATS_SCRIPT = /<script src="stats\.js[^"]*"><\/script>/;
await copyFile(join(here, "player-facts.js"), join(build, "coevo-player-facts.js"));
await copyFile(join(here, "search.js"), join(build, "coevo-search.js"));
const v = Date.now();
await writeFile(join(build, "search.html"), play.replace(STATS_SCRIPT, "").replace(marker, (m) =>
  `<script src="coevo-player-facts.js?v=${v}"></script>\n  <script src="coevo-search.js?v=${v}"></script>\n  ${m}`));

// A kind of badguys: a mode of the page (off, coevo4, ...) or "table:<name>",
// one of the badguy tables in tools/coevo/tables.
async function aiQuery(kind) {
  const ai = kind.replace(/~$/, "");
  const extra = kind.endsWith("~") ? `&noise=${noise}` : "";
  if (!ai.startsWith("table:"))
    return `ai=${ai}${extra}`;
  const name = ai.slice(6);
  await copyFile(join(tablesDir, `${name}.js`), join(build, `${name}-table.js`));
  return `ai=table&table=${encodeURIComponent(name)}${extra}`;
}

const browser = await chromium.launch({ headless: true, channel: "chromium", args: ["--mute-audio"] });
// However this process ends (an error included), the browser goes with it:
// left behind, its games keep the memory the next run needs.
process.on("exit", () => { try { browser.process()?.kill("SIGKILL"); } catch {} });
const pages = {};
// Opened a few at a time: twenty pages loading at once time out.
for (const ai of pageKinds) {
  pages[ai] = [];
  for (let t = 0; t < tabs; t++) {
    const page = await (await browser.newContext({ viewport: { width: 640, height: 360 } })).newPage()  // own storage: the game keeps its config and saves there;
    page.on("pageerror", (e) => console.error("pageerror", e.message));
    await page.goto(`http://127.0.0.1:8765/search.html?${await aiQuery(ai)}&v=${v}`, { timeout: 300000 });
    pages[ai].push(page);
  }
  await Promise.all(pages[ai].map(async (page) => {
    await page.waitForFunction(() => document.title.startsWith("SuperTux"), null, { timeout: 300000 });
    await page.waitForTimeout(1000);
    await page.evaluate(() => window.__search_ready());
  }));
}

/** Runs jobs on the pages of one kind of badguys. */
async function onPages(ai, jobs) {
  const results = new Array(jobs.length);
  let next = 0;
  await Promise.all(pages[ai].map(async (page) => {
    while (next < jobs.length) {
      const i = next++;
      results[i] = await jobs[i](page);
    }
  }));
  return results;
}

/** How the table (or a changed one) does in every case: [{ ai, seed, result }]. */
/** Plays one case: the waits, then the table. The pairs are the table's own. */
async function playCase(page, t, c) {
  const r = await page.evaluate(([t, seed, turbo, waits]) =>
    window.__search_policy(112, 576, 13380, waits, t, turbo, seed, 300), [t, c.seed, TURBO, Array(c.delay).fill(2)]);
  return { ...r, pairs: r.pairs.slice(c.delay) };
}

const allCases = () => [
  ...ais.flatMap((ai) => seeds.flatMap((seed) => delays.map((delay) => ({ ai, seed, delay })))),
  ...noisyAis.flatMap((ai) => noiseSeeds.map((seed) => ({ ai: ai + "~", seed, delay: 0 }))),
];

async function evaluate(delta = table.delta) {
  const t = { ...table, delta };
  const cases = allCases();
  const byAi = await Promise.all(pageKinds.map((ai) => {
    const mine = cases.filter((c) => c.ai === ai);
    return onPages(ai, mine.map((c) => (page) => playCase(page, t, c))).then((rs) => rs.map((r, i) => [mine[i], r]));
  }));
  const found = new Map(byAi.flat().map(([c, r]) => [c, r]));
  return cases.map((c) => ({ ...c, result: found.get(c) }));
}

const score = (cases) => cases.reduce((sum, c) => sum + (c.result.reached ? GOAL + 1000 : c.result.maxX), 0);
const summary = (cases) => cases.map((c) => `${c.ai}/${c.seed}${c.delay ? "+" + c.delay : ""} ${c.result.reached ? "GOAL" : c.result.maxX}`).join(", ");

/** Beam search from after `prefix` for moves that get past `goal` alive. */
async function searchFrom(ai, seed, prefix, goal, fixed) {
  let beam = [[]];
  for (let depth = 1; depth <= DEPTH && beam.length; depth++) {
    const sequences = beam.flatMap((s) => Array.from({ length: MOVES }, (_, m) => [...s, m]));
    const results = await onPages(ai, sequences.map((s) => (page) =>
      page.evaluate(([moves, zones, seed, fixed, turbo]) => window.__search_try(112, 576, 1e9, moves, zones, turbo, seed, null, 300, fixed),
                    [[...prefix, ...s], zones, seed, fixed, TURBO])));
    const ends = new Map();
    for (let i = 0; i < sequences.length; i++) {
      const r = results[i];
      if (r.alive && (r.x >= goal || r.reached))
        return { moves: sequences[i], pairs: r.pairs.slice(prefix.length) };
      if (!r.alive)
        continue;
      const key = `${Math.round(r.x / CELL)} ${Math.round(r.y / CELL)} ${r.ground}`;
      const s = r.x + 0.8 * (START.bottom - r.y);
      if (!ends.has(key) || ends.get(key).score < s) ends.set(key, { score: s, seq: sequences[i] });
    }
    beam = [...ends.values()].sort((a, b) => b.score - a.score).slice(0, BEAM).map((e) => e.seq);
  }
  return null;
}

// --- rounds -------------------------------------------------------------------
//
// A beam of tables: each round, for the table's run that got least far, the
// last few moves it chose before it got as far as it did are each changed to every other
// move, one at a time; every such table plays every run, and the ones that
// get furthest in all (the goal counting extra) go on. Since one table plays
// every kind of badguys, a change that helps one run and breaks another
// scores no better, and the tables that go on are ones that serve all.

const LAST = Number(args.last || 10);        // moves before a failure that may change
const KEEP = Number(args.keep || 6);        // tables kept each round
const WORST = Number(args.worst || 3);      // runs whose moves may change, the ones that got least far
const GIVE_UP = 2;                          // rounds spent on a place without getting past it
const tries = new Map();                    // where runs failed (in tiles) -> rounds spent there

let beam = [{ delta: { ...table.delta }, cases: await evaluate(), verified: true }];
console.log(`start: ${summary(beam[0].cases)}`);
await save();  // written even if nothing better is found
const seen = new Set([JSON.stringify(beam[0].delta)]);
let best = beam[0];
for (let round = 1; round <= ROUNDS; round++) {
  const children = [];
  for (const parent of beam) {
    // The few runs that got least far, each where it failed only once, and
    // not the ones changes have not helped for a while: each may be the one
    // a change helps.
    const places = new Set();
    const failing = parent.cases.filter((c) => !c.result.reached)
      .sort((a, b) => a.result.maxX - b.result.maxX)
      .filter((c) => {
        const place = Math.round(c.result.maxX / 32);
        if (places.has(place) || (tries.get(place) || 0) >= GIVE_UP) return false;
        places.add(place);
        return true;
      })
      .slice(0, WORST);
    for (const c of failing) {
      const place = Math.round(c.result.maxX / 32);
      tries.set(place, (tries.get(place) || 0) + 1);
    }
    for (const worst of failing) {
      // The moves before he got as far as he did: once stuck, the rest are
      // the same few moves over and over.
      const decided = worst.result.pairs;
      const reachedAt = decided.findIndex((p) => p[2] >= worst.result.maxX - 48);
      const upTo = reachedAt < 0 ? decided.length : reachedAt + 1;
      for (const [index, move] of decided.slice(Math.max(0, upTo - LAST), upTo)) {
        for (let m = 0; m < MOVES; m++) {
          if (m === move) continue;
          const delta = { ...parent.delta, [index]: m };
          const key = JSON.stringify(delta);
          if (seen.has(key)) continue;
          seen.add(key);
          children.push({ delta, parent, changed: index });
        }
      }
    }
  }
  if (!children.length) {
    console.log(`round ${round}: nothing left to try`);
    break;
  }
  // Every child plays every run; spread over the pages.
  const scored = [];
  let next = 0;
  await Promise.all(Array.from({ length: tabs }, async (_, tab) => {
    while (next < children.length) {
      const { delta, parent, changed } = children[next++];
      const t = { ...table, delta };
      // Each kind of badguys has its own page: those play at once. A run
      // that never met the situation changed plays out as it did.
      const cases = allCases();
      const cs = new Array(cases.length);
      await Promise.all(pageKinds.map(async (ai) => {
        for (let i = 0; i < cases.length; i++) {
          if (cases[i].ai !== ai) continue;
          const before = parent.cases[i];
          cs[i] = before.result.pairs.some((p) => p[0] === changed) ? { ...cases[i], result: await playCase(pages[ai][tab], t, cases[i]) }
                                                                    : before;
        }
      }));
      scored.push({ delta, cases: cs });
    }
  }));
  const pool = [...beam, ...scored].sort((a, b) => score(b.cases) - score(a.cases));
  // Different results only: many changes do nothing at all.
  const kept = new Map();
  for (const entry of pool) {
    const key = summary(entry.cases);
    if (!kept.has(key)) kept.set(key, entry);
    if (kept.size >= KEEP) break;
  }
  beam = [...kept.values()];
  // The best is played again in full before it counts: the runs taken over
  // from its parent have been seen to differ now and then.
  for (let check = 0; check < beam.length && !beam[0].verified; check++) {
    const verified = await evaluate(beam[0].delta);
    if (summary(verified) !== summary(beam[0].cases))
      console.log(`round ${round}: played again, the best does ${summary(verified)}`);
    beam[0] = { ...beam[0], cases: verified, verified: true };
    beam.sort((a, b) => score(b.cases) - score(a.cases));
  }
  if (score(beam[0].cases) > score(best.cases)) {
    best = beam[0];
    table.delta = best.delta;
    await save();
  }
  console.log(`round ${round}: ${children.length} tables tried, best ${summary(best.cases)}`);
  if (best.cases.every((c) => c.result.reached)) {
    console.log(`round ${round}: every run gets to the goal`);
    break;
  }
}
console.log(`end: ${summary(best.cases)}; ${Object.keys(table.delta).length} situations differ from ${args.from}'s plain table`);
// Closing the browser has been seen to hang; the work is saved by now.
await Promise.race([browser.close().catch(() => {}), new Promise((r) => setTimeout(r, 10000))]);
try { browser.process()?.kill("SIGKILL"); } catch {}
process.exit(0);
