// Generated by tools/laya-server/export-table.mjs from mk/emscripten/laya-prompt.js; do not edit.
window.LAYA_TABLE = {
  "model": "aac6fef/laya-mlx",
  "instructions": "Which action fits my situation?",
  "criteria": {
    "charge": "open ground, player ahead",
    "retreat": "falling onto me, invincible, danger",
    "hold": "wall, player far away",
    "jump": "ledge above, wall close"
  },
  "answers": {
    "The player is on open ground ahead of me, touching.": {
      "type": "choice",
      "choice": "charge",
      "confidence": 0.2991,
      "probabilities": {
        "charge": 0.6725,
        "retreat": 0.1093,
        "hold": 0.1556,
        "jump": 0.0625
      }
    },
    "The player is invincible.": {
      "type": "choice",
      "choice": "charge",
      "confidence": 0.0461,
      "probabilities": {
        "charge": 0.3711,
        "retreat": 0.1349,
        "hold": 0.287,
        "jump": 0.2071
      }
    },
    "A wall blocks my way and the player is close.": {
      "type": "choice",
      "choice": "hold",
      "confidence": 0.3786,
      "probabilities": {
        "charge": 0.1457,
        "retreat": 0.0737,
        "hold": 0.727,
        "jump": 0.0536
      }
    },
    "The player stands on a ledge right above me.": {
      "type": "choice",
      "choice": "jump",
      "confidence": 0.7032,
      "probabilities": {
        "charge": 0.0365,
        "retreat": 0.0222,
        "hold": 0.035,
        "jump": 0.9064
      }
    },
    "The player is above me and falling onto me.": {
      "type": "choice",
      "choice": "charge",
      "confidence": 0.0936,
      "probabilities": {
        "charge": 0.3501,
        "retreat": 0.2894,
        "hold": 0.0601,
        "jump": 0.3004
      }
    },
    "The player is on open ground ahead of me, near.": {
      "type": "choice",
      "choice": "charge",
      "confidence": 0.3358,
      "probabilities": {
        "charge": 0.6979,
        "retreat": 0.0823,
        "hold": 0.1573,
        "jump": 0.0625
      }
    },
    "The player is on open ground ahead of me, medium.": {
      "type": "choice",
      "choice": "charge",
      "confidence": 0.6121,
      "probabilities": {
        "charge": 0.8652,
        "retreat": 0.0422,
        "hold": 0.0624,
        "jump": 0.0302
      }
    },
    "A wall blocks my way and the player is far away.": {
      "type": "choice",
      "choice": "hold",
      "confidence": 0.687,
      "probabilities": {
        "charge": 0.0393,
        "retreat": 0.0342,
        "hold": 0.8999,
        "jump": 0.0265
      }
    },
    "The player is on open ground ahead of me, far.": {
      "type": "choice",
      "choice": "charge",
      "confidence": 0.6139,
      "probabilities": {
        "charge": 0.8653,
        "retreat": 0.036,
        "hold": 0.0673,
        "jump": 0.0315
      }
    }
  }
};
